### ISSUE TITLE
Failed to install enigma2

### ISSUE THREAD

**Issue by zwada** [Xento/pimatic-enigma2#1]
10:13:01.239 [pimatic, npm] info: http GET https://registry.npmjs.org/pimatic-enigma2
10:13:02.293 [pimatic, npm] info: http 200 https://registry.npmjs.org/pimatic-enigma2
10:13:02.360 [pimatic, npm] info: http GET https://registry.npmjs.org/pimatic-enigma2/-/pimatic-enigma2-0.1.1.tgz
10:13:03.001 [pimatic, npm] info: http 200 https://registry.npmjs.org/pimatic-enigma2/-/pimatic-enigma2-0.1.1.tgz
10:13:03.751 [pimatic, npm] info: http GET https://registry.npmjs.org/Restler/3.2.2
10:13:04.086 [pimatic, npm] info: http 404 https://registry.npmjs.org/Restler/3.2.2
10:13:04.136 [pimatic, npm] info: ERR! 404 'Restler' is not in the npm registry.
10:13:04.144 [pimatic, npm] info: ERR! 404 You should bug the author to publish it
10:13:04.147 [pimatic, npm] info: ERR! 404 
10:13:04.152 [pimatic, npm] info: ERR! 404 Note that you can also install from a
10:13:04.155 [pimatic, npm] info: ERR! 404 tarball, folder, or http url, or git url.
10:13:04.159 [pimatic, npm] info: ERR! System Linux 3.18.11-v7+
10:13:04.162 [pimatic, npm] info: ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-enigma2"
10:13:04.185 [pimatic, npm] info: ERR! cwd /home/pi/pimatic-app
10:13:04.188 [pimatic, npm] info: ERR! node -v v0.10.24
10:13:04.190 [pimatic, npm] info: ERR! npm -v 1.3.21
10:13:04.193 [pimatic, npm] info: ERR! code E404
10:13:04.216 [pimatic, npm] info: ERR! 
10:13:04.220 [pimatic, npm] info: ERR! Additional logging details can be found in:
10:13:04.223 [pimatic, npm] info: ERR!     /home/pi/pimatic-app/npm-debug.log
10:13:04.225 [pimatic, npm] info: ERR! not ok code 0

**Comment by Xento** [comment]
Can you try again?
I think the problem was that I wrote restler with an uppercase beginning.
I fixed this.

**Comment by Xento** [comment]
Is it fixed?

**Comment by zwada** [comment]
if the problem is solved thanks
